# PR Review Agent Configuration
git_providers:
  - name: github
    api_token: "YOUR_GITHUB_TOKEN_HERE"
    base_url: "https://api.github.com"

ai:
  enabled: false  # Start with false to test basic functionality

analysis:
  enable_security_scan: true
  enable_performance_scan: false
  enable_style_scan: false
  enable_complexity_scan: false

log_level: INFO
